-- ---
-- Globals
-- ---

-- SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
-- SET FOREIGN_KEY_CHECKS=0;

-- ---
-- Table 'USERS'
-- Users Table
-- ---

DROP TABLE IF EXISTS `USERS`;

CREATE TABLE `USERS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `login` MEDIUMTEXT NULL,
  `password` MEDIUMTEXT NULL DEFAULT NULL,
  `email` MEDIUMTEXT NULL DEFAULT NULL,
  `first_name` MEDIUMTEXT NULL DEFAULT NULL,
  `last_name` MEDIUMTEXT NULL DEFAULT NULL,
  `created_on` TIMESTAMP NULL DEFAULT NULL,
  `last_login` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) COMMENT 'Users Table';

-- ---
-- Table 'QUESTIONS'
--
-- ---

DROP TABLE IF EXISTS `QUESTIONS`;

CREATE TABLE `QUESTIONS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `created_by` INTEGER NULL DEFAULT NULL,
  `is_public` INTEGER NULL DEFAULT NULL,
  `created_on` TIMESTAMP NULL DEFAULT NULL,
  `type` MEDIUMTEXT NULL DEFAULT NULL,
  `category` MEDIUMTEXT NULL DEFAULT NULL,
  `prompt` MEDIUMTEXT NULL DEFAULT NULL,
  `choices` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'DECKS'
--
-- ---

DROP TABLE IF EXISTS `DECKS`;

CREATE TABLE `DECKS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `created_by` INTEGER NULL DEFAULT NULL,
  `is_public` INTEGER NULL DEFAULT NULL,
  `created_on` TIMESTAMP NULL DEFAULT NULL,
  `title` MEDIUMTEXT NULL DEFAULT NULL,
  `subject` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'GAMES'
--
-- ---

DROP TABLE IF EXISTS `GAMES`;

CREATE TABLE `GAMES` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `created_on` TIMESTAMP NULL DEFAULT NULL,
  `concluded_on` TIMESTAMP NULL DEFAULT NULL,
  `deck_id` INTEGER NULL DEFAULT NULL,
  `started_by` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'RESPONSES'
--
-- ---

DROP TABLE IF EXISTS `RESPONSES`;

CREATE TABLE `RESPONSES` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `game_id` INTEGER NULL DEFAULT NULL,
  `player_id` INTEGER NULL DEFAULT NULL,
  `question_id` INTEGER NULL DEFAULT NULL,
  `answer_provided` MEDIUMTEXT NULL DEFAULT NULL,
  `is_correct` INTEGER NULL DEFAULT NULL,
  `point_value` INTEGER NULL DEFAULT NULL,
  `max_point_value` INTEGER NULL DEFAULT NULL,
  `asked_on` TIMESTAMP NULL DEFAULT NULL,
  `response_time_ms` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'QUESTIONS_KEYWORDS'
--
-- ---

DROP TABLE IF EXISTS `QUESTIONS_KEYWORDS`;

CREATE TABLE `QUESTIONS_KEYWORDS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `question` INTEGER NULL DEFAULT NULL,
  `keyword` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'USERS_DECKS'
--
-- ---

DROP TABLE IF EXISTS `USERS_DECKS`;

CREATE TABLE `USERS_DECKS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `user` INTEGER NULL DEFAULT NULL,
  `deck` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'DECKS_QUESTIONS'
--
-- ---

DROP TABLE IF EXISTS `DECKS_QUESTIONS`;

CREATE TABLE `DECKS_QUESTIONS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `deck` INTEGER NULL DEFAULT NULL,
  `question` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'GAMES_PLAYERS'
--
-- ---

DROP TABLE IF EXISTS `GAMES_PLAYERS`;

CREATE TABLE `GAMES_PLAYERS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `game` INTEGER NULL DEFAULT NULL,
  `player` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Table 'KEYWORDS'
--
-- ---

DROP TABLE IF EXISTS `KEYWORDS`;

CREATE TABLE `KEYWORDS` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `word` MEDIUMTEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

-- ---
-- Foreign Keys
-- ---

ALTER TABLE `QUESTIONS` ADD FOREIGN KEY (created_by) REFERENCES `USERS` (`id`);
ALTER TABLE `DECKS` ADD FOREIGN KEY (created_by) REFERENCES `USERS` (`id`);
ALTER TABLE `GAMES` ADD FOREIGN KEY (started_by) REFERENCES `USERS` (`id`);
ALTER TABLE `RESPONSES` ADD FOREIGN KEY (game_id) REFERENCES `GAMES` (`id`);
ALTER TABLE `RESPONSES` ADD FOREIGN KEY (player_id) REFERENCES `USERS` (`id`);
ALTER TABLE `RESPONSES` ADD FOREIGN KEY (question_id) REFERENCES `QUESTIONS` (`id`);
ALTER TABLE `QUESTIONS_KEYWORDS` ADD FOREIGN KEY (question) REFERENCES `QUESTIONS` (`id`);
ALTER TABLE `QUESTIONS_KEYWORDS` ADD FOREIGN KEY (keyword) REFERENCES `KEYWORDS` (`id`);
ALTER TABLE `USERS_DECKS` ADD FOREIGN KEY (user) REFERENCES `USERS` (`id`);
ALTER TABLE `USERS_DECKS` ADD FOREIGN KEY (deck) REFERENCES `DECKS` (`id`);
ALTER TABLE `DECKS_QUESTIONS` ADD FOREIGN KEY (deck) REFERENCES `DECKS` (`id`);
ALTER TABLE `DECKS_QUESTIONS` ADD FOREIGN KEY (question) REFERENCES `QUESTIONS` (`id`);
ALTER TABLE `GAMES_PLAYERS` ADD FOREIGN KEY (game) REFERENCES `GAMES` (`id`);
ALTER TABLE `GAMES_PLAYERS` ADD FOREIGN KEY (player) REFERENCES `USERS` (`id`);

-- ---
-- Table Properties
-- ---

-- ALTER TABLE `USERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `QUESTIONS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `DECKS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `GAMES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `RESPONSES` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `QUESTIONS_KEYWORDS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `USERS_DECKS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `DECKS_QUESTIONS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `GAMES_PLAYERS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
-- ALTER TABLE `KEYWORDS` ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

-- ---
-- Test Data
-- ---

-- INSERT INTO `USERS` (`id`,`login`,`password`,`email`,`first_name`,`last_name`,`created_on`,`last_login`) VALUES
-- ('','','','','','','','');
-- INSERT INTO `QUESTIONS` (`id`,`created_by`,`is_public`,`created_on`,`type`,`category`,`prompt`,`choices`) VALUES
-- ('','','','','','','','');
-- INSERT INTO `DECKS` (`id`,`created_by`,`is_public`,`created_on`,`title`,`subject`) VALUES
-- ('','','','','','');
-- INSERT INTO `GAMES` (`id`,`created_on`,`concluded_on`,`deck_id`,`started_by`) VALUES
-- ('','','','','');
-- INSERT INTO `RESPONSES` (`id`,`game_id`,`player_id`,`question_id`,`answer_provided`,`is_correct`,`point_value`,`max_point_value`,`asked_on`,`response_time_ms`) VALUES
-- ('','','','','','','','','','');
-- INSERT INTO `QUESTIONS_KEYWORDS` (`id`,`question`,`keyword`) VALUES
-- ('','','');
-- INSERT INTO `USERS_DECKS` (`id`,`user`,`deck`) VALUES
-- ('','','');
-- INSERT INTO `DECKS_QUESTIONS` (`id`,`deck`,`question`) VALUES
-- ('','','');
-- INSERT INTO `GAMES_PLAYERS` (`id`,`game`,`player`) VALUES
-- ('','','');
-- INSERT INTO `KEYWORDS` (`id`,`word`) VALUES
-- ('','');
